### ISSUE TITLE
Column read issue in `np.loadtxt()`

### ISSUE THREAD

**Issue by Luke-ebbis** [Luke-ebbis/PSPHunter#1]
In `Intest-apply.test.py`,  an issue occurs when annotating the human proteome

```bash
✨ Pixi task (default): perl scripts/Standalone/predict_proteinProb.pl xargs -i results/data/UP000005640/fasta/proteome.fasta -o /results/data/UP000005640/annotation/psp-hunter/proteome
82493
Traceback (most recent call last):
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/scripts/Standalone/Intest-apply-test.py", line 17, in <module>
    matrixI = np.loadtxt(direct2 + 'Intestinput.txt')
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/.pixi/envs/default/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/.pixi/envs/default/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1016, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 61 to 1 at row 4091; use `usecols` to select a subset and avoid this error
Traceback (most recent call last):
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/scripts/Standalone/Intest-apply-test.py", line 17, in <module>
    matrixI = np.loadtxt(direct2 + 'Intestinput.txt')
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/.pixi/envs/default/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/.pixi/envs/default/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1016, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 61 to 1 at row 4091; use `usecols` to select a subset and avoid this error
Traceback (most recent call last):
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/scripts/Standalone/Intest-apply-test.py", line 17, in <module>
    matrixI = np.loadtxt(direct2 + 'Intestinput.txt')
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/.pixi/envs/default/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/.pixi/envs/default/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1016, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 61 to 1 at row 4091; use `usecols` to select a subset and avoid this error
Traceback (most recent call last):
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/scripts/Standalone/Intest-apply-test.py", line 17, in <module>
    matrixI = np.loadtxt(direct2 + 'Intestinput.txt')
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/.pixi/envs/default/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/mpimp-golm.mpg.de/bakker6625/Documents/experiments/LLPS/workflow/scripts/dependencies/PSPHunter/.pixi/envs/default/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1016, in _read
```

**Comment by Luke-ebbis** [comment]
Well, it seems that newlines are not printed correctly in the perl script...

```bash
>trH7C012H7C012_
QLCPGWLGPTSTSAVQLFLLGEMEPAGEKDEPLSVKHGRPMKCPSQESPYLFSYRNSNYLTRLQKPQDKLEVREGAEIRCPDKDPSDTVPTSVHRLKPADINVIGALGDSLTAGNGAGSTPGNVLDVLTQYRGLSWSVGGDENIGTVTTLANILREFNPSLKGFSVGTGKETSPNAFLNQAVAGGRAEDLPVQARRLVDLMKNDTRIHFQEDWKIITLFIGGNDLCDFCNDLVHYSPQNFTDNIGKALDILHAEVPRAFVNLVTVLEIVNLRELYQEKKVYCPRMILRSLCPCVLKFDDNSTELATLIEFNKKFQEKTHQLIESGRYDTREDFTVVVQPFFENVDMPKTSEGLPDNSFFAPDCFHFSSKSHSRAASALWNNMLEPVGQKTTRHKFENKINITCPNQVQPFLRTYKNSMQGHGTWLPCRDRAPSALHPTSVHALRPADIQVVAALGDSLTAGNGIGSKPDDLPDVTTQYRGLSYRESKPGFLSDSWVSKSNRKCTRKAPNP>trH7C012H7C012_
QLCPGWLGPTSTSAVQLFLLGEMEPAGEKDEPLSVKHGRPMKCPSQESPYLFSYRNSNYLTRLQKPQDKLEVREGAEIRCPDKDPSDTVPTSVHRLKPADINVIGALGDSLTAGNGAGSTPGNVLDVLTQYRGLSWSVGGDENIGTVTTLANILREFNPSLKGFSVGTGKETSPNAFLNQAVAGGRAEDLPVQARRLVDLMKNDTRIHFQEDWKIITLFIGGNDLCDFCNDLVHYSPQNFTDNIGKALDILHAEVPRAFVNLVTVLEIVNLRELYQEKKVYCPRMILRSLCPCVLKFDDNSTELATLIEFNKKFQEKTHQLIESGRYDTREDFTVVVQPFFENVDMPKTSEGLPDNSFFAPDCFHFSSKSHSRAASALWNNMLEPVGQKTTRHKFENKINITCPNQVQPFLRTYKNSMQGHGTWLPCRDRAPSALHPTSVHALRPADIQVVAALGDSLTAGNGIGSKPDDLPDVTTQYRGLSYRESKPGFLSDSWVSKSNRKCTRKAPNUser@computer ~ $
```

Even worse, the FASTA file seem duplicated somehow
